import type { Metadata } from "next";
import { DM_Sans, Space_Grotesk } from "next/font/google";
import "./globals.css";
import  { Wallet } from "@/context/WalletProvider";
import Footer from "@/components/widgets/Footer";
import { Toaster } from "react-hot-toast";
import Script from "next/script";

const spaceGro = Space_Grotesk({
  variable: "--font-space-gro",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dmSans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${spaceGro.variable} ${dmSans.variable} antialiased`}
      >
        <Wallet>
          <Toaster />
          {children}
        </Wallet>
      </body>
    </html>
  );
}
