import type { Metadata } from "next";
import { DM_Sans, Space_Grotesk } from "next/font/google";
import "./globals.css";
import  { Wallet } from "@/context/WalletProvider";

const spaceGro = Space_Grotesk({
  variable: "--font-space-gro",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dmSans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGro.variable} ${dmSans.variable} antialiased`}
      >
        <Wallet>
          {children}
        </Wallet>
        
      </body>
    </html>
  );
}
